//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftServerManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftServerManager.Resources.LanguageEN", typeof(LanguageEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD SERVER.
        /// </summary>
        internal static string AddServerMenu {
            get {
                return ResourceManager.GetString("AddServerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        internal static string AgreeEula {
            get {
                return ResourceManager.GetString("AgreeEula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BrowseDirectory {
            get {
                return ResourceManager.GetString("BrowseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect local server.
        /// </summary>
        internal static string ConnectLocalServer {
            get {
                return ResourceManager.GetString("ConnectLocalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect remote server.
        /// </summary>
        internal static string ConnectRemoteServer {
            get {
                return ResourceManager.GetString("ConnectRemoteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        internal static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HALT.
        /// </summary>
        internal static string ConsoleKill {
            get {
                return ResourceManager.GetString("ConsoleKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTART.
        /// </summary>
        internal static string ConsoleRestart {
            get {
                return ResourceManager.GetString("ConsoleRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUN.
        /// </summary>
        internal static string ConsoleRun {
            get {
                return ResourceManager.GetString("ConsoleRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string ConsoleStop {
            get {
                return ResourceManager.GetString("ConsoleStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string CopyClipboard {
            get {
                return ResourceManager.GetString("CopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy dorectory.
        /// </summary>
        internal static string CopyDirectory {
            get {
                return ResourceManager.GetString("CopyDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file.
        /// </summary>
        internal static string CopyFile {
            get {
                return ResourceManager.GetString("CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP data:.
        /// </summary>
        internal static string DataFtp {
            get {
                return ResourceManager.GetString("DataFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCON data:.
        /// </summary>
        internal static string DataRcon {
            get {
                return ResourceManager.GetString("DataRcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete directory &quot;{0}&quot;?
        ///This operation can&apos;t be undone!.
        /// </summary>
        internal static string DialogDirectoryRemove {
            get {
                return ResourceManager.GetString("DialogDirectoryRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete file &quot;{0}&quot;?
        ///This operation can&apos;t be undone!.
        /// </summary>
        internal static string DialogFileRemove {
            get {
                return ResourceManager.GetString("DialogFileRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete remote server &quot;{0}&quot; from your server list?.
        /// </summary>
        internal static string DialogRemoteServerRemove {
            get {
                return ResourceManager.GetString("DialogRemoteServerRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete server &quot;{0}&quot;?
        ///This operation can&apos;t be undone!.
        /// </summary>
        internal static string DialogServerRemove {
            get {
                return ResourceManager.GetString("DialogServerRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create directory.
        /// </summary>
        internal static string DirectoryCreate {
            get {
                return ResourceManager.GetString("DirectoryCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new directory name:.
        /// </summary>
        internal static string DirectoryNameChange {
            get {
                return ResourceManager.GetString("DirectoryNameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new directory name:.
        /// </summary>
        internal static string DirectoryNameInput {
            get {
                return ResourceManager.GetString("DirectoryNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New directory.
        /// </summary>
        internal static string DirectoryNew {
            get {
                return ResourceManager.GetString("DirectoryNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting download....
        /// </summary>
        internal static string DownloadBegin {
            get {
                return ResourceManager.GetString("DownloadBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        internal static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred downloading server engine!.
        /// </summary>
        internal static string DownloadErrorServer {
            get {
                return ResourceManager.GetString("DownloadErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download finished.
        /// </summary>
        internal static string DownloadFinished {
            get {
                return ResourceManager.GetString("DownloadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file.
        /// </summary>
        internal static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading server engine: {0}/{1}.
        /// </summary>
        internal static string DownloadProgressServer {
            get {
                return ResourceManager.GetString("DownloadProgressServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine:.
        /// </summary>
        internal static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading server engine. Are you sure want to cancel?.
        /// </summary>
        internal static string EngineEditorAbort {
            get {
                return ResourceManager.GetString("EngineEditorAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked engines will be downloaded and unchecked will be deleted..
        /// </summary>
        internal static string EngineEditorHeader {
            get {
                return ResourceManager.GetString("EngineEditorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize engines.
        /// </summary>
        internal static string EngineEditorName {
            get {
                return ResourceManager.GetString("EngineEditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} engines will be downloaded and {1} engines will be removed.
        ///Are you sure want to continue?.
        /// </summary>
        internal static string EngineEditorPerform {
            get {
                return ResourceManager.GetString("EngineEditorPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory with this name already exists!.
        /// </summary>
        internal static string ErrorDirectoryExists {
            get {
                return ResourceManager.GetString("ErrorDirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid directory name!.
        /// </summary>
        internal static string ErrorDirectoryInvalidName {
            get {
                return ResourceManager.GetString("ErrorDirectoryInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected directory must contain server engine!.
        /// </summary>
        internal static string ErrorEngineNotInDirectory {
            get {
                return ResourceManager.GetString("ErrorEngineNotInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with this name already exists!.
        /// </summary>
        internal static string ErrorFileExists {
            get {
                return ResourceManager.GetString("ErrorFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name!.
        /// </summary>
        internal static string ErrorFileInvalidName {
            get {
                return ResourceManager.GetString("ErrorFileInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open file, because it&apos;s not text file!.
        /// </summary>
        internal static string ErrorFileNotText {
            get {
                return ResourceManager.GetString("ErrorFileNotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open file, because it&apos;s too big!.
        /// </summary>
        internal static string ErrorFileTooBig {
            get {
                return ResourceManager.GetString("ErrorFileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open file!.
        /// </summary>
        internal static string ErrorFileUnknown {
            get {
                return ResourceManager.GetString("ErrorFileUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect with FTP server! Are you sure you entered correct data?.
        /// </summary>
        internal static string ErrorFtp {
            get {
                return ResourceManager.GetString("ErrorFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP port must be number!.
        /// </summary>
        internal static string ErrorNanPortFtp {
            get {
                return ResourceManager.GetString("ErrorNanPortFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCON port must be number!.
        /// </summary>
        internal static string ErrorNanPortRcon {
            get {
                return ResourceManager.GetString("ErrorNanPortRcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory!.
        /// </summary>
        internal static string ErrorNoDirectory {
            get {
                return ResourceManager.GetString("ErrorNoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select engine!.
        /// </summary>
        internal static string ErrorNoEngine {
            get {
                return ResourceManager.GetString("ErrorNoEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree with Mojang EULA!.
        /// </summary>
        internal static string ErrorNoEula {
            get {
                return ResourceManager.GetString("ErrorNoEula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter FTP data!.
        /// </summary>
        internal static string ErrorNoFtpData {
            get {
                return ResourceManager.GetString("ErrorNoFtpData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select JAR file!.
        /// </summary>
        internal static string ErrorNoJar {
            get {
                return ResourceManager.GetString("ErrorNoJar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter RCON data!.
        /// </summary>
        internal static string ErrorNoRconData {
            get {
                return ResourceManager.GetString("ErrorNoRconData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter server IP!.
        /// </summary>
        internal static string ErrorNoServerIp {
            get {
                return ResourceManager.GetString("ErrorNoServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter server name!.
        /// </summary>
        internal static string ErrorNoServerName {
            get {
                return ResourceManager.GetString("ErrorNoServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter style name!.
        /// </summary>
        internal static string ErrorNoStyleName {
            get {
                return ResourceManager.GetString("ErrorNoStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select version!.
        /// </summary>
        internal static string ErrorNoVersion {
            get {
                return ResourceManager.GetString("ErrorNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP port number is out of range!.
        /// </summary>
        internal static string ErrorOorPortFtp {
            get {
                return ResourceManager.GetString("ErrorOorPortFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCON port number is out of range!.
        /// </summary>
        internal static string ErrorOorPortRcon {
            get {
                return ResourceManager.GetString("ErrorOorPortRcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t complete operation, because of error!.
        /// </summary>
        internal static string ErrorOperationUnknown {
            get {
                return ResourceManager.GetString("ErrorOperationUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect with server console by RCON! Are you sure you entered correct data?
        ///Remember to insert the following lines in server.properties:
        ///enable-rcon=true
        ///rcon.port=Your RCON port
        ///rcon.password=Your RCON password.
        /// </summary>
        internal static string ErrorRcon {
            get {
                return ResourceManager.GetString("ErrorRcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server with this name already exists!.
        /// </summary>
        internal static string ErrorServerExists {
            get {
                return ResourceManager.GetString("ErrorServerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name is invalid!.
        /// </summary>
        internal static string ErrorServerInvalidName {
            get {
                return ResourceManager.GetString("ErrorServerInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in file explorer.
        /// </summary>
        internal static string ExplorerOpen {
            get {
                return ResourceManager.GetString("ExplorerOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create file.
        /// </summary>
        internal static string FileCreate {
            get {
                return ResourceManager.GetString("FileCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new file name:.
        /// </summary>
        internal static string FileNameChange {
            get {
                return ResourceManager.GetString("FileNameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new file name:.
        /// </summary>
        internal static string FileNameInput {
            get {
                return ResourceManager.GetString("FileNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        internal static string FileNew {
            get {
                return ResourceManager.GetString("FileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft - Server manager.
        /// </summary>
        internal static string FullProgramName {
            get {
                return ResourceManager.GetString("FullProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP adress:.
        /// </summary>
        internal static string IpAdress {
            get {
                return ResourceManager.GetString("IpAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE LOCAL SERVER.
        /// </summary>
        internal static string MenuAddServerLocal {
            get {
                return ResourceManager.GetString("MenuAddServerLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECT LOCAL SERVER.
        /// </summary>
        internal static string MenuConnectServerLocal {
            get {
                return ResourceManager.GetString("MenuConnectServerLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECT REMOTE SERVER.
        /// </summary>
        internal static string MenuConnectServerRemote {
            get {
                return ResourceManager.GetString("MenuConnectServerRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGLISH.
        /// </summary>
        internal static string MenuEnglish {
            get {
                return ResourceManager.GetString("MenuEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLISH.
        /// </summary>
        internal static string MenuPolish {
            get {
                return ResourceManager.GetString("MenuPolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGANIZE ENGINES.
        /// </summary>
        internal static string MenuSettingsEngines {
            get {
                return ResourceManager.GetString("MenuSettingsEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE STYLES.
        /// </summary>
        internal static string MenuSettingsStyles {
            get {
                return ResourceManager.GetString("MenuSettingsStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move directory.
        /// </summary>
        internal static string MoveDirectory {
            get {
                return ResourceManager.GetString("MoveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move file.
        /// </summary>
        internal static string MoveFile {
            get {
                return ResourceManager.GetString("MoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        internal static string NameChangeButton {
            get {
                return ResourceManager.GetString("NameChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        internal static string NameChangeTitle {
            get {
                return ResourceManager.GetString("NameChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New directory.
        /// </summary>
        internal static string NewDirectory {
            get {
                return ResourceManager.GetString("NewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        internal static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading server engine. Are you sure want to cancel?.
        /// </summary>
        internal static string NewLocalServerAbort {
            get {
                return ResourceManager.GetString("NewLocalServerAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New local server.
        /// </summary>
        internal static string NewLocalServerName {
            get {
                return ResourceManager.GetString("NewLocalServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not downloaded.
        /// </summary>
        internal static string NotDownloaded {
            get {
                return ResourceManager.GetString("NotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherFemale {
            get {
                return ResourceManager.GetString("OtherFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherMale {
            get {
                return ResourceManager.GetString("OtherMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste clipboard.
        /// </summary>
        internal static string PasteClipboard {
            get {
                return ResourceManager.GetString("PasteClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERFORM.
        /// </summary>
        internal static string PerformButton {
            get {
                return ResourceManager.GetString("PerformButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server manager.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected directory:.
        /// </summary>
        internal static string SelectedDirectory {
            get {
                return ResourceManager.GetString("SelectedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file:.
        /// </summary>
        internal static string SelectedFile {
            get {
                return ResourceManager.GetString("SelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select server directory:.
        /// </summary>
        internal static string SelectServerDirectory {
            get {
                return ResourceManager.GetString("SelectServerDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select server engine file:.
        /// </summary>
        internal static string SelectServerFile {
            get {
                return ResourceManager.GetString("SelectServerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server {0} has been stopped.
        /// </summary>
        internal static string ServerHalted {
            get {
                return ResourceManager.GetString("ServerHalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping server {0}....
        /// </summary>
        internal static string ServerHalting {
            get {
                return ResourceManager.GetString("ServerHalting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting server {0}....
        /// </summary>
        internal static string ServerLaunching {
            get {
                return ResourceManager.GetString("ServerLaunching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new server name:.
        /// </summary>
        internal static string ServerNameChange {
            get {
                return ResourceManager.GetString("ServerNameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting server {0}....
        /// </summary>
        internal static string ServerRestarting {
            get {
                return ResourceManager.GetString("ServerRestarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR SERVERS:.
        /// </summary>
        internal static string ServersTreeHeader {
            get {
                return ResourceManager.GetString("ServersTreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add style:.
        /// </summary>
        internal static string StyleAdd {
            get {
                return ResourceManager.GetString("StyleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD STYLE.
        /// </summary>
        internal static string StyleAddButton {
            get {
                return ResourceManager.GetString("StyleAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright gold (built-in).
        /// </summary>
        internal static string StyleBrightGold {
            get {
                return ResourceManager.GetString("StyleBrightGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window background color:.
        /// </summary>
        internal static string StyleColorBack {
            get {
                return ResourceManager.GetString("StyleColorBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls background color:.
        /// </summary>
        internal static string StyleColorControl {
            get {
                return ResourceManager.GetString("StyleColorControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text and icons color:.
        /// </summary>
        internal static string StyleColorFore {
            get {
                return ResourceManager.GetString("StyleColorFore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark (built-in).
        /// </summary>
        internal static string StyleDark {
            get {
                return ResourceManager.GetString("StyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage styles.
        /// </summary>
        internal static string StyleEditorName {
            get {
                return ResourceManager.GetString("StyleEditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style name:.
        /// </summary>
        internal static string StyleName {
            get {
                return ResourceManager.GetString("StyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select style:.
        /// </summary>
        internal static string StyleSelect {
            get {
                return ResourceManager.GetString("StyleSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting upload....
        /// </summary>
        internal static string UploadBegin {
            get {
                return ResourceManager.GetString("UploadBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file.
        /// </summary>
        internal static string UploadProgress {
            get {
                return ResourceManager.GetString("UploadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File  &quot;{0}&quot; hasn&apos;t been saved! Do you want to save it?.
        /// </summary>
        internal static string WarningFileNotSaved {
            get {
                return ResourceManager.GetString("WarningFileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the language, program must be restarted. Are you sure want to do this?.
        /// </summary>
        internal static string WarningLanguageChange {
            get {
                return ResourceManager.GetString("WarningLanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to halt process of server &quot;{0}&quot;? It&apos;s recommend to use safe button &quot;stop&quot;..
        /// </summary>
        internal static string WarningServerKill {
            get {
                return ResourceManager.GetString("WarningServerKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server &quot;{0}&quot; still running! Are you sure want to halt it?.
        /// </summary>
        internal static string WarningServerRunning {
            get {
                return ResourceManager.GetString("WarningServerRunning", resourceCulture);
            }
        }
    }
}
