//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftServerManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguagePL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguagePL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftServerManager.Resources.LanguagePL", typeof(LanguagePL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DODAJ SERWER.
        /// </summary>
        internal static string AddServerMenu {
            get {
                return ResourceManager.GetString("AddServerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akceptuję postanowienia.
        /// </summary>
        internal static string AgreeEula {
            get {
                return ResourceManager.GetString("AgreeEula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj....
        /// </summary>
        internal static string BrowseDirectory {
            get {
                return ResourceManager.GetString("BrowseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podłącz serwer lokalny.
        /// </summary>
        internal static string ConnectLocalServer {
            get {
                return ResourceManager.GetString("ConnectLocalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podłącz serwer zdalny.
        /// </summary>
        internal static string ConnectRemoteServer {
            get {
                return ResourceManager.GetString("ConnectRemoteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsola.
        /// </summary>
        internal static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAKOŃCZ.
        /// </summary>
        internal static string ConsoleKill {
            get {
                return ResourceManager.GetString("ConsoleKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTARTUJ.
        /// </summary>
        internal static string ConsoleRestart {
            get {
                return ResourceManager.GetString("ConsoleRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URUCHOM.
        /// </summary>
        internal static string ConsoleRun {
            get {
                return ResourceManager.GetString("ConsoleRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZATRZYMAJ.
        /// </summary>
        internal static string ConsoleStop {
            get {
                return ResourceManager.GetString("ConsoleStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj do schowka.
        /// </summary>
        internal static string CopyClipboard {
            get {
                return ResourceManager.GetString("CopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj folder.
        /// </summary>
        internal static string CopyDirectory {
            get {
                return ResourceManager.GetString("CopyDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj plik.
        /// </summary>
        internal static string CopyFile {
            get {
                return ResourceManager.GetString("CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane FTP:.
        /// </summary>
        internal static string DataFtp {
            get {
                return ResourceManager.GetString("DataFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane RCON:.
        /// </summary>
        internal static string DataRcon {
            get {
                return ResourceManager.GetString("DataRcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć folder &quot;{0}&quot;?
        ///Tej operacji nie można będzie cofnąć!.
        /// </summary>
        internal static string DialogDirectoryRemove {
            get {
                return ResourceManager.GetString("DialogDirectoryRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć plik &quot;{0}&quot;?
        ///Tej operacji nie można będzie cofnąć!.
        /// </summary>
        internal static string DialogFileRemove {
            get {
                return ResourceManager.GetString("DialogFileRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć serwer zdalny &quot;{0}&quot; z listy swoich serwerów?.
        /// </summary>
        internal static string DialogRemoteServerRemove {
            get {
                return ResourceManager.GetString("DialogRemoteServerRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć serwer &quot;{0}&quot;?
        ///Tej operacji nie można będzie cofnąć!.
        /// </summary>
        internal static string DialogServerRemove {
            get {
                return ResourceManager.GetString("DialogServerRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz folder.
        /// </summary>
        internal static string DirectoryCreate {
            get {
                return ResourceManager.GetString("DirectoryCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nową nazwę folderu:.
        /// </summary>
        internal static string DirectoryNameChange {
            get {
                return ResourceManager.GetString("DirectoryNameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę nowego folderu:.
        /// </summary>
        internal static string DirectoryNameInput {
            get {
                return ResourceManager.GetString("DirectoryNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy folder.
        /// </summary>
        internal static string DirectoryNew {
            get {
                return ResourceManager.GetString("DirectoryNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobieranie.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczynam pobieranie....
        /// </summary>
        internal static string DownloadBegin {
            get {
                return ResourceManager.GetString("DownloadBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobrano.
        /// </summary>
        internal static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobieranie silnika.
        /// </summary>
        internal static string DownloadEngine {
            get {
                return ResourceManager.GetString("DownloadEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas pobierania silnika serwera!.
        /// </summary>
        internal static string DownloadErrorServer {
            get {
                return ResourceManager.GetString("DownloadErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobieranie zakończone.
        /// </summary>
        internal static string DownloadFinished {
            get {
                return ResourceManager.GetString("DownloadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobieranie pliku.
        /// </summary>
        internal static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobieranie silnika serwera: {0}/{1}.
        /// </summary>
        internal static string DownloadProgressServer {
            get {
                return ResourceManager.GetString("DownloadProgressServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silnik:.
        /// </summary>
        internal static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trwa pobieranie silnika serwera. Czy chcesz je anulować?.
        /// </summary>
        internal static string EngineEditorAbort {
            get {
                return ResourceManager.GetString("EngineEditorAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznaczone silniki zostaną pobrane, a nie zaznaczone usunięte..
        /// </summary>
        internal static string EngineEditorHeader {
            get {
                return ResourceManager.GetString("EngineEditorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizuj silniki.
        /// </summary>
        internal static string EngineEditorName {
            get {
                return ResourceManager.GetString("EngineEditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostanie pobrane {0} silników i usunięte {1} silników.
        ///Czy chcesz kontynuować?.
        /// </summary>
        internal static string EngineEditorPerform {
            get {
                return ResourceManager.GetString("EngineEditorPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder o podanej nazwie już istnieje!.
        /// </summary>
        internal static string ErrorDirectoryExists {
            get {
                return ResourceManager.GetString("ErrorDirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana nazwa folderu jest nieprawidłowa!.
        /// </summary>
        internal static string ErrorDirectoryInvalidName {
            get {
                return ResourceManager.GetString("ErrorDirectoryInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silnik serwera musi znajdować się w wybranym folderze!.
        /// </summary>
        internal static string ErrorEngineNotInDirectory {
            get {
                return ResourceManager.GetString("ErrorEngineNotInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik o podanej nazwie już istnieje!.
        /// </summary>
        internal static string ErrorFileExists {
            get {
                return ResourceManager.GetString("ErrorFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana nazwa pliku jest nieprawidłowa!.
        /// </summary>
        internal static string ErrorFileInvalidName {
            get {
                return ResourceManager.GetString("ErrorFileInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można otworzyć pliku, ponieważ nie jest on plikiem tekstowym!.
        /// </summary>
        internal static string ErrorFileNotText {
            get {
                return ResourceManager.GetString("ErrorFileNotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można otworzyć pliku, ponieważ jest za duży!.
        /// </summary>
        internal static string ErrorFileTooBig {
            get {
                return ResourceManager.GetString("ErrorFileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można otworzyć pliku!.
        /// </summary>
        internal static string ErrorFileUnknown {
            get {
                return ResourceManager.GetString("ErrorFileUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się połączyć z serwerem FTP! Czy na pewno wpisałeś poprawne dane?.
        /// </summary>
        internal static string ErrorFtp {
            get {
                return ResourceManager.GetString("ErrorFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer portu FTP musi być liczbą!.
        /// </summary>
        internal static string ErrorNanPortFtp {
            get {
                return ResourceManager.GetString("ErrorNanPortFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer portu RCON musi być liczbą!.
        /// </summary>
        internal static string ErrorNanPortRcon {
            get {
                return ResourceManager.GetString("ErrorNanPortRcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz folder!.
        /// </summary>
        internal static string ErrorNoDirectory {
            get {
                return ResourceManager.GetString("ErrorNoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz silnik!.
        /// </summary>
        internal static string ErrorNoEngine {
            get {
                return ResourceManager.GetString("ErrorNoEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz zaakceptować postanowienia Mojang EULA!.
        /// </summary>
        internal static string ErrorNoEula {
            get {
                return ResourceManager.GetString("ErrorNoEula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj dane FTP!.
        /// </summary>
        internal static string ErrorNoFtpData {
            get {
                return ResourceManager.GetString("ErrorNoFtpData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz plik .jar!.
        /// </summary>
        internal static string ErrorNoJar {
            get {
                return ResourceManager.GetString("ErrorNoJar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj dane RCON!.
        /// </summary>
        internal static string ErrorNoRconData {
            get {
                return ResourceManager.GetString("ErrorNoRconData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj adres IP serwera!
        ///.
        /// </summary>
        internal static string ErrorNoServerIp {
            get {
                return ResourceManager.GetString("ErrorNoServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę serwera!.
        /// </summary>
        internal static string ErrorNoServerName {
            get {
                return ResourceManager.GetString("ErrorNoServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa stylu nie może być pusta!.
        /// </summary>
        internal static string ErrorNoStyleName {
            get {
                return ResourceManager.GetString("ErrorNoStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz wersję!.
        /// </summary>
        internal static string ErrorNoVersion {
            get {
                return ResourceManager.GetString("ErrorNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer portu FTP jest poza zakresem!.
        /// </summary>
        internal static string ErrorOorPortFtp {
            get {
                return ResourceManager.GetString("ErrorOorPortFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer portu RCON jest poza zakresem!.
        /// </summary>
        internal static string ErrorOorPortRcon {
            get {
                return ResourceManager.GetString("ErrorOorPortRcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można ukończyć operacji z powodu błędu!.
        /// </summary>
        internal static string ErrorOperationUnknown {
            get {
                return ResourceManager.GetString("ErrorOperationUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się połączyć z konsolą serwera przez RCON! Czy na pewno wpisałeś poprawne dane?
        ///Pamiętaj o wstawieniu w pliku server.properties następujących linii:
        ///enable-rcon=true
        ///rcon.port=Twój port RCON
        ///rcon.password=Twoje hasło RCON.
        /// </summary>
        internal static string ErrorRcon {
            get {
                return ResourceManager.GetString("ErrorRcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serwer o podanej nazwie już istnieje!.
        /// </summary>
        internal static string ErrorServerExists {
            get {
                return ResourceManager.GetString("ErrorServerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana nazwa serwera jest nieprawidłowa!.
        /// </summary>
        internal static string ErrorServerInvalidName {
            get {
                return ResourceManager.GetString("ErrorServerInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz w eksploratorze plików.
        /// </summary>
        internal static string ExplorerOpen {
            get {
                return ResourceManager.GetString("ExplorerOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz plik.
        /// </summary>
        internal static string FileCreate {
            get {
                return ResourceManager.GetString("FileCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nową nazwę pliku:.
        /// </summary>
        internal static string FileNameChange {
            get {
                return ResourceManager.GetString("FileNameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę nowego pliku:.
        /// </summary>
        internal static string FileNameInput {
            get {
                return ResourceManager.GetString("FileNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy plik.
        /// </summary>
        internal static string FileNew {
            get {
                return ResourceManager.GetString("FileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft - Menedżer serwera.
        /// </summary>
        internal static string FullProgramName {
            get {
                return ResourceManager.GetString("FullProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres IP:.
        /// </summary>
        internal static string IpAdress {
            get {
                return ResourceManager.GetString("IpAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencja.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTWÓRZ SERWER LOKALNY.
        /// </summary>
        internal static string MenuAddServerLocal {
            get {
                return ResourceManager.GetString("MenuAddServerLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PODŁĄCZ SERWER LOKALNY.
        /// </summary>
        internal static string MenuConnectServerLocal {
            get {
                return ResourceManager.GetString("MenuConnectServerLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PODŁĄCZ SERWER ZDALNY.
        /// </summary>
        internal static string MenuConnectServerRemote {
            get {
                return ResourceManager.GetString("MenuConnectServerRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANGIELSKI.
        /// </summary>
        internal static string MenuEnglish {
            get {
                return ResourceManager.GetString("MenuEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JĘZYK.
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLSKI.
        /// </summary>
        internal static string MenuPolish {
            get {
                return ResourceManager.GetString("MenuPolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGANIZUJ SILNIKI.
        /// </summary>
        internal static string MenuSettingsEngines {
            get {
                return ResourceManager.GetString("MenuSettingsEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZARZĄDZAJ STYLAMI.
        /// </summary>
        internal static string MenuSettingsStyles {
            get {
                return ResourceManager.GetString("MenuSettingsStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przenieś folder.
        /// </summary>
        internal static string MoveDirectory {
            get {
                return ResourceManager.GetString("MoveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przenieś plik.
        /// </summary>
        internal static string MoveFile {
            get {
                return ResourceManager.GetString("MoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień nazwę.
        /// </summary>
        internal static string NameChangeButton {
            get {
                return ResourceManager.GetString("NameChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana nazwy.
        /// </summary>
        internal static string NameChangeTitle {
            get {
                return ResourceManager.GetString("NameChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy folder.
        /// </summary>
        internal static string NewDirectory {
            get {
                return ResourceManager.GetString("NewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy plik.
        /// </summary>
        internal static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trwa pobieranie silnika serwera. Czy chcesz je anulować.
        /// </summary>
        internal static string NewLocalServerAbort {
            get {
                return ResourceManager.GetString("NewLocalServerAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy serwer lokalny.
        /// </summary>
        internal static string NewLocalServerName {
            get {
                return ResourceManager.GetString("NewLocalServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie pobrano.
        /// </summary>
        internal static string NotDownloaded {
            get {
                return ResourceManager.GetString("NotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inna.
        /// </summary>
        internal static string OtherFemale {
            get {
                return ResourceManager.GetString("OtherFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inny.
        /// </summary>
        internal static string OtherMale {
            get {
                return ResourceManager.GetString("OtherMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wklej ze schowka.
        /// </summary>
        internal static string PasteClipboard {
            get {
                return ResourceManager.GetString("PasteClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WYKONAJ.
        /// </summary>
        internal static string PerformButton {
            get {
                return ResourceManager.GetString("PerformButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menedżer serwera.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gotowe.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień nazwę.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrano folder:.
        /// </summary>
        internal static string SelectedDirectory {
            get {
                return ResourceManager.GetString("SelectedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrano plik:.
        /// </summary>
        internal static string SelectedFile {
            get {
                return ResourceManager.GetString("SelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz folder z serwerem:.
        /// </summary>
        internal static string SelectServerDirectory {
            get {
                return ResourceManager.GetString("SelectServerDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz plik silnika serwera:.
        /// </summary>
        internal static string SelectServerFile {
            get {
                return ResourceManager.GetString("SelectServerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serwer {0} został zatrzymany..
        /// </summary>
        internal static string ServerHalted {
            get {
                return ResourceManager.GetString("ServerHalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymywanie serwera {0}....
        /// </summary>
        internal static string ServerHalting {
            get {
                return ResourceManager.GetString("ServerHalting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchamianie serwera {0}....
        /// </summary>
        internal static string ServerLaunching {
            get {
                return ResourceManager.GetString("ServerLaunching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nową nazwę serwera:.
        /// </summary>
        internal static string ServerNameChange {
            get {
                return ResourceManager.GetString("ServerNameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponowne uruchamianie serwera {0}....
        /// </summary>
        internal static string ServerRestarting {
            get {
                return ResourceManager.GetString("ServerRestarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWOJE SERWERY:.
        /// </summary>
        internal static string ServersTreeHeader {
            get {
                return ResourceManager.GetString("ServersTreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USTAWIENIA.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj styl:.
        /// </summary>
        internal static string StyleAdd {
            get {
                return ResourceManager.GetString("StyleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DODAJ STYL.
        /// </summary>
        internal static string StyleAddButton {
            get {
                return ResourceManager.GetString("StyleAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jasne złoto (wbudowany).
        /// </summary>
        internal static string StyleBrightGold {
            get {
                return ResourceManager.GetString("StyleBrightGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolor tła okna:.
        /// </summary>
        internal static string StyleColorBack {
            get {
                return ResourceManager.GetString("StyleColorBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolor tła kontrolek:.
        /// </summary>
        internal static string StyleColorControl {
            get {
                return ResourceManager.GetString("StyleColorControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolor tekstu i ikon:.
        /// </summary>
        internal static string StyleColorFore {
            get {
                return ResourceManager.GetString("StyleColorFore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciemny (wbudowany).
        /// </summary>
        internal static string StyleDark {
            get {
                return ResourceManager.GetString("StyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj stylami.
        /// </summary>
        internal static string StyleEditorName {
            get {
                return ResourceManager.GetString("StyleEditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa stylu:.
        /// </summary>
        internal static string StyleName {
            get {
                return ResourceManager.GetString("StyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz styl:.
        /// </summary>
        internal static string StyleSelect {
            get {
                return ResourceManager.GetString("StyleSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysyłanie.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczynam wysyłanie....
        /// </summary>
        internal static string UploadBegin {
            get {
                return ResourceManager.GetString("UploadBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysyłanie pliku.
        /// </summary>
        internal static string UploadProgress {
            get {
                return ResourceManager.GetString("UploadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik:.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja:.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostrzeżenie.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik  &quot;{0}&quot;nie został zapisany! Czy chcesz go zapisać?.
        /// </summary>
        internal static string WarningFileNotSaved {
            get {
                return ResourceManager.GetString("WarningFileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby zmienić język konieczny jest restart programu. Czy na pewno chcesz to zrobić?.
        /// </summary>
        internal static string WarningLanguageChange {
            get {
                return ResourceManager.GetString("WarningLanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz zakończyć proces serwera &quot;{0}&quot;? Zalecane jest używanie bezpiecznego przycisku &quot;zatrzymaj&quot;..
        /// </summary>
        internal static string WarningServerKill {
            get {
                return ResourceManager.GetString("WarningServerKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serwer &quot;{0}&quot; wciąż działa! Czy na pewno chcesz go wyłączyć?.
        /// </summary>
        internal static string WarningServerRunning {
            get {
                return ResourceManager.GetString("WarningServerRunning", resourceCulture);
            }
        }
    }
}
